providers = ["node"]

[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ["npm install -g corepack", "corepack enable", "corepack prepare pnpm@latest --activate", "pnpm install"]

[phases.build]
cmds = ["pnpm build"]
